name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Step 1: Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Step 2: Run Snyk for SCA (Software Composition Analysis)
      - name: Run Snyk to check for vulnerabilities in dependencies (SCA)
        uses: snyk/actions/maven@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

       # Step 3: Run Snyk for SAST (Static Application Security Testing)
      - name: Run Snyk SAST to check for vulnerabilities in source code
        run: |
          snyk code test --all-projects --sarif-file-output=snyk_sast.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        # Step 4: Upload SCA results to GitHub Code Scanning
      - name: Upload SCA result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_sca.sarif

       # Step 5: Upload SAST results to GitHub Code Scanning
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
